---
name: Publish
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-lts"

jobs:
  publish:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Starting Report
        run: |
          echo Git Ref: ${{ github.ref }}
          echo GitHub Event: ${{ github.event_name }}
          echo Disk usage
          df -h
          echo Memory
          free -m
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Force fetch annotated tags (workaround)
        # Workaround for https://github.com/actions/checkout/issues/290
        run: |
          git fetch --force --tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            lfedge/eve-build-tools
          tags: |
            type=sha                        # if we merge into main, publish with a short git commit tag
            type=semver,pattern={{version}} # if we publish a git tag, use that git tag as the image tag
            type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}  # the head of main always should have the tag `main`
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

